### ISSUE TITLE
就我一个人觉得这个入门文档写的太杂乱无章 难懂吗?

### ISSUE THREAD

**Issue by kingrocy** [orlabs/orange#286]
如题：

从orange官网进来，在官网上没有找到入门文档，进入github，

读了三四遍 readme ，都没有发现怎么使用orange 快速开始。。

**Comment by shuaijinchao** [comment]
we released a new version of `0.8.0`, which solved the problem of dependent installation through `lualocks`.
you can experience our new `v0.8.0` version. if you find any problems, please feel free to provide feedback through the `issues`.
