### ISSUE TITLE
v0.70 配置好之后访问 / 报错 

### ISSUE THREAD

**Issue by saonek** [orlabs/orange#287]
`2019/07/30 20:23:37 [error] 25605#0: *57 lua entry thread aborted: runtime error: /usr/local/orange/orange/plugins/balancer/handler.lua:34: variable "target" not found for writing; maybe it is a built-in variable that is not changeable or you forgot to use "set $target '';" in the config file to define it first
stack traceback:
coroutine 0:
	[C]: in function '__newindex'
	/usr/local/orange/orange/plugins/balancer/handler.lua:34: in function 'access'
	/usr/local/orange/orange/orange.lua:165: in function 'access'
	access_by_lua(nginx.conf:113):3: in function <access_by_lua(nginx.conf:113):1>, client: 192.168.33.1, server: , request: "GET /login HTTP/1.1", host: "192.168.33.10:8100"
2019/07/30 20:23:37 [info] 25605#0: *57 [lua] handler.lua:65: log(): ==[Monitor][PASS THROUGH SELECTOR:06a77ee7-37f4-470f-8656-a82d97f65dfa] while logging request, client: 192.168.33.1, server: , request: "GET /login HTTP/1.1", host: "192.168.33.10:8100"
`

**Comment by saonek** [comment]
配置rewrite  也是 报如上的错误。

**Comment by liulei18** [comment]
* First of all, when you use Orange,you should to have a clear understanding of OpenResty and know Orange's plugins how to loaded and works in which request phase
* For example, the following nginx config snippet will work as expected
```
        location /test{
                rewrite_by_lua_block {
                        local orange = context.orange
                        orange.redirect()
                        orange.rewrite()
                }

                access_by_lua_block {
                        local orange = context.orange
                        orange.access()
                }

                # content phase
                echo "Hello Orange";

                header_filter_by_lua_block {
                        local orange = context.orange
                        orange.header_filter()
                }

                body_filter_by_lua_block {
                        local orange = context.orange
                        orange.body_filter()
                }
                log_by_lua_block {
                        local orange = context.orange
                        orange.log()
                }
        }
```

**Comment by qinxiaogit** [comment]
这个要初始化target

**Comment by hj4444** [comment]
> 这个要初始化target

能具体点吗

**Comment by liulei18** [comment]
> > 这个要初始化target
> 
> 能具体点吗



> * First of all, when you use Orange,you should to have a clear understanding of OpenResty and know Orange's plugins how to loaded and works in which request phase
> * For example, the following nginx config snippet will work as expected
> 
> ```
>         location /test{
>                 set $target '';
>                 rewrite_by_lua_block {
>                         local orange = context.orange
>                         orange.redirect()
>                         orange.rewrite()
>                 }
> 
>                 access_by_lua_block {
>                         local orange = context.orange
>                         orange.access()
>                 }
> 
>                 # content phase
>                 echo "Hello Orange";
> 
>                 header_filter_by_lua_block {
>                         local orange = context.orange
>                         orange.header_filter()
>                 }
> 
>                 body_filter_by_lua_block {
>                         local orange = context.orange
>                         orange.body_filter()
>                 }
>                 log_by_lua_block {
>                         local orange = context.orange
>                         orange.log()
>                 }
>         }
> ```

* By the way, $target 变量是balancer插件所使用的的变量，，想进一步了解，请查看balancer插件源码/plugins/balancer/handler.lua --line34 ,使用变量之前必须先定义：请在nginx.conf中定义target变量：set $target ''; 就可以了

**Comment by shuaijinchao** [comment]
hope that you can solve your problem through the above answer. If you have any questions, you can use us to send us feedback again.
