### ISSUE TITLE
orange安装好了，关机后/usr/local/orange/的配置就会丢失，必须到安装包make install

### ISSUE THREAD

**Issue by yangjietest** [orlabs/orange#290]
你好，大佬，为什么我把orange安装好了，关机后/usr/local/orange/的配置就会丢失，必须到安装包make install，然后测才能启动，就是lublib那个目录。环境推到了几次还是那样，centos的版本也换了几个，还是不行，求助。。。。

**Comment by liulei18** [comment]
* 首先Orange的安装方式有两种，
1. 一种是直接解压即可使用，通过执行解压目录下的sh start.sh即可
2. 通过make install,将会将Orange安装到默认目录：/usr/local/orange，以及将CLI tools 安装到/usr/local/bin/orange，更多详情可以参看Makefile文件，了解make install时做了哪些操作
* 你说的 ```/usr/local/orange/的配置就会丢失```具体是什么配置，请将issue描述清楚

**Comment by yangjietest** [comment]
我是用的第二种方式安装的，目录在/usr/local/bin/orange，安装好了，启动没问题，但是只要重启服务器，就会提示 dns.Client的模块找不到，对比原来安装的就丢失了lublib那个目录，不知道什么原因

**Comment by liulei18** [comment]
* 执行 ```` opm --install-dir=./ get zhangbao0325/orangelib      //opm download the 3rd packages ```会将第三方插件的依赖安装到 lualib文件夹中
1. 根据你的描述，系统重启后，lualib文件中某些.lua文件丢失，猜想是你环境问题，你可以通过查看系统日志，看重启系统前后是否有文件删除操作

**Comment by yangjietest** [comment]
对，我是执行了的，安装好了可以正常启动的，但一重启就
[INFO] ORANGE_CONF=/usr/local/orange/conf/orange.conf nginx -p /usr/local/orange -c /usr/local/orange/conf/nginx.conf 
nginx: [error] [lua] orange.lua:75: init(): Startup error: /usr/local/orange/orange/utils/utils.lua:192: ./lualib/resty/dns/balancer.lua:48: module 'random' not found:
	no field package.preload['random']
	no file './lualib/random.lua'
	no file './lualib/resty/random.lua'
	no file '/usr/local/orange/random.lua'
	no file '/usr/local/lor/random.lua'
	no file '/usr/local/luarocks/share/lua/5.1/random.lua'
	no file '/usr/local/openresty/site/lualib/random.ljbc'
	no file '/usr/local/openresty/site/lualib/random/init.ljbc'
	no file '/usr/local/openresty/lualib/random.ljbc'
	no file '/usr/local/openresty/lualib/random/init.ljbc'
	no file '/usr/local/openresty/site/lualib/random.lua'
	no file '/usr/local/openresty/site/lualib/random/init.lua'
	no file '/usr/local/openresty/lualib/random.lua'
	no file '/usr/local/openresty/lualib/random/init.lua'
	no file './random.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/random.lua'
	no file '/usr/local/share/lua/5.1/random.lua'
	no file '/usr/local/share/lua/5.1/random/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/random.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/random/init.lua'
	no file '/usr/local/luarocks/lib/lua/5.1/random.so'
	no file '/usr/local/luarocks/lib/lua/5.1/socket/random.so'
	no file '/usr/local/luarocks/lib/lua/5.1/mime/random.so'
	no file '/usr/local/openresty/site/lualib/random.so'
	no file '/usr/local/openresty/lualib/random.so'
	no file './random.so'
	no file '/usr/local/lib/lua/5.1/random.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/random.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
但是我安装那个模块，有提示我已经装了
[root@localuser orange]# /usr/local/openresty/bin/opm --install-dir=./ get xiangnanscu/lua-resty-random
Package lua-resty-random-1.0 already installed.

**Comment by liulei18** [comment]
* 移除你安装的lua-resty-random依赖，这个是错误的依赖
* 通过执行 #luarocks install lrandom 可以安装random相关依赖
* 如果想要了解更多，see also https://github.com/orlabs/orange/issues/281#issuecomment-512768900

**Comment by yangjietest** [comment]
好的，谢谢。丢配置问题已经找到了，目前使用的是 nginx -p `pwd` -c ./conf/nginx.conf 的方式启动，正常使用中

**Comment by wujunze** [comment]
谢谢解答 最近比较忙  忙完这一阵子 会更新 Orange   解决安装不流畅的问题

**Comment by yangjietest** [comment]
对对，大佬是要优化下orange安装的问题，多谢😂

**Comment by shuaijinchao** [comment]
we released a new version of `0.8.0`, which solved the problem of dependent installation through `lualocks`.
hope version `0.8.0` can solve your problem.

**Comment by shuaijinchao** [comment]
you can experience our new `v0.8.0` version. If you find any problems, please feel free to provide feedback through the `issues`.

**Comment by yangjietest** [comment]
好的，谢谢。测试安装中
------------------ 原始邮件 ------------------
发件人: "Janko"<notifications@github.com>;
发送时间: 2019年10月17日(星期四) 晚上10:25
收件人: "orlabs/orange"<orange@noreply.github.com>;
抄送: "Yangjie"<991990023@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [orlabs/orange] orange安装好了，关机后/usr/local/orange/的配置就会丢失，必须到安装包make install (#290)




Closed #290.
