### ISSUE TITLE
谁能提供一份orange的完整的安装部署文档

### ISSUE THREAD

**Issue by mingluyang** [orlabs/orange#297]
哪位大神能提供一份orange完整的安装部署文档，我自己试着安装了一次，可以安装上，但是我第二天发现又起不来了，报了各种依赖不存在，但是我去找，他们都是存在的。所以想要一份完整的基础安装步骤。谢谢了

**Comment by shuaijinchao** [comment]
We released a new version of `0.8.0`, which solved the problem of dependent installation through `lualocks`.

**Comment by shuaijinchao** [comment]
hope version `0.8.0` can solve your problem.

**Comment by mingluyang** [comment]
thank you



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Janko <notifications@github.com&gt;
发送时间: 2019年10月17日 22:15
收件人: orlabs/orange <orange@noreply.github.com&gt;
抄送: mingluyang <296989235@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[orlabs/orange] 谁能提供一份orange的完整的安装部署文档 (#297)




hope version 0.8.0 can solve your problem.

**Comment by shuaijinchao** [comment]
you can experience our new `v0.8.0` version. if you find any problems, please feel free to provide feedback through the `issues`.
