### ISSUE TITLE
feature: support `luarocks` mode for installation and deployment.

### ISSUE THREAD

**Issue by shuaijinchao** [orlabs/orange#300]
Because different operating system distributions have different dependencies and installation steps, in order to avoid installation problems caused by system dependencies, we will provide `luarocks` as the new default installation method.
Support `Orange` version: v0.8.0

由于不同的操作系统发行版本有不同的依赖和安装步骤，为了避免系统依赖导致的安装问题，我们将提供`luarocks`作为新的默认安装方式。
支持 `Orange` 版本：v0.8.0

**Comment by wujunze** [comment]
👍   很棒的方式
