### ISSUE TITLE
bug: luarocks install `api` directory does not exist.

### ISSUE THREAD

**Issue by shuaijinchao** [orlabs/orange#314]
Causes the API Server 7777 port to be inaccessible.

**Comment by liulei18** [comment]
* `api` directory is not download with `git clone https://github.com/orlabs/orange.git`  when executes `sh install.sh`?

**Comment by shuaijinchao** [comment]
> * `api` directory is not download with `git clone https://github.com/orlabs/orange.git`  when executes `sh install.sh`?

the clone `orange` project was completed by `luarocks`, and the `api` directory was omitted during the `Makefile` installation process.

**Comment by shuaijinchao** [comment]
this issues fixed #315 @liulei18
