### ISSUE TITLE
建议nginx默认配置中增加proxy_set_header host

### ISSUE THREAD

**Issue by magaofei** [orlabs/orange#333]
##### 使用的Orange版本

v0.8.0

##### 需求或场景

使用分流/代理插件时，我将流量转发到另外一台nginx上，但是丢失了 host 参数，经过查看，加上 `proxy_set_header Host $host:$server_port;` 就好了，建议默认的 `nginx.conf` 带上这个参数，或者加一行注释也可以，便于用户使用

##### 使用的插件

分流/代理

**Comment by shuaijinchao** [comment]
Thanks for the feedback, we will add this feature to the plan.

---

感谢反馈，我们将把此需求加入到计划中。

**Comment by magaofei** [comment]
我提了一个 PR

**Comment by shuaijinchao** [comment]
Thanks @magaofei , PR(#334) Merged. Please close issues.
