### ISSUE TITLE
同步orange节点功能无效

### ISSUE THREAD

**Issue by magaofei** [orlabs/orange#353]
##### 使用的Orange版本

v0.8.0

##### 需求或场景

添加了3个节点后，在一个节点上更改配置，点击同步orange节点，其他节点并未进行配置更改

##### 错误的结果
![image](https://user-images.githubusercontent.com/3363787/69128636-ba725680-0ae7-11ea-9b2a-f6b4221d0ed9.png)
![image](https://user-images.githubusercontent.com/3363787/69129115-bb57b800-0ae8-11ea-8242-78c70ab41658.png)

**Comment by magaofei** [comment]
@shuaijinchao @wujunze

**Comment by blmdxiao** [comment]
检查一下orange.conf中是否启用了node插件，默认配置是没有启用node插件。

**Comment by blmdxiao** [comment]
"plugins": [
        "stat",
        "headers",
        "monitor",
        "redirect",
        "rewrite",
        "rate_limiting",
        "property_rate_limiting",
        "basic_auth",
        "key_auth",
        "jwt_auth",
        "hmac_auth",
        "signature_auth",
        "waf",
        "divide",
        "node"
    ],

@magaofei

**Comment by magaofei** [comment]
我试一下

**Comment by magaofei** [comment]
调试了大半天终于成功了
1. 先开启node节点插件
2. 使用一个节点作为主节点，点击“注册节点”
3. 添加其他服务器作为节点，点击“新增节点”添加。
4. 在主节点上进行操作，然后同步

**Comment by imocat** [comment]
> 调试了大半天终于成功了
> 
> 1. 先开启node节点插件
> 2. 使用一个节点作为主节点，点击“注册节点”
> 3. 添加其他服务器作为节点，点击“新增节点”添加。
> 4. 在主节点上进行操作，然后同步

是的，我是插件作者，抱歉没有及时回复。

**Comment by magaofei** [comment]
@imocat 问了一圈，orange 其他核心贡献者都不知道这个是怎么用的…，终于让我给试出来了，最后提交了一个pr文档

**Comment by wujunze** [comment]
> @imocat 问了一圈，orange 其他核心贡献者都不知道这个是怎么用的…，终于让我给试出来了，最后提交了一个pr文档

优秀 👍   你可以翻下代码实现  哈哈哈     欢迎加入开发组
