### ISSUE TITLE
optimize: update `error.log` default level to error in `nginx.conf.example`.

### ISSUE THREAD

**Issue by magaofei** [orlabs/orange#354]
##### 使用的Orange版本

v0.8.0

##### 需求或场景

1. `error.log` 里存在大量的 info 级别的日志，很奇怪
2. 日志量巨大，一周1百万的请求量，error.log 日志大小7G

**Comment by shuaijinchao** [comment]
hi, @magaofei 
PR (#355) Merged, please close this issues.
